version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
      - mongodb
    volumes:
      - .:/app

  worker:
    build: .
    command: celery -A app.worker worker --loglevel=info
    env_file:
      - .env
    depends_on:
      - redis
      - mongodb
    volumes:
      - .:/app

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: 